sudo: required

services:
  - docker

env:
  global:
    - VERSION=3.9-0.9.7-0.13.7
    - DOCKER_LOGIN=crazymax
    - DOCKER_USERNAME=crazymax
    - DOCKER_REPONAME=rtorrent-rutorrent
    - QUAY_LOGIN=crazymax
    - QUAY_USERNAME=crazymax
    - QUAY_REPONAME=rtorrent-rutorrent
    - secure: aL467eTsXh/TyinxRTVf189zMr5LxLtbwDQIc2he5uJy3hqLcjSUEKtqFZ+RvePlHAFqRJQ+sg/Te8A6k11+lMf08Mu4lxbE33+wWlB6Mx8l8FV90fiDusZt6RQcCm0HKuhA1mk2uLnuPW3SJR+dvdgs4Vsee8xqbgJytEbu2/YFWPwm1pOC/I2ZGXk1769sBNrL9NYZBrXOjSDsbUa91hioGNjhUHRQ6lpzNPbxRCDqkwZS7ORnhcQe4r+EjecGPQwPOVTRvzkP0klUUvHknquEQ98acyv3tTy2zO2QYzaZ9dvD8ga26aChXc+0hhgs7QOY799Ok0A+hKWZxXH5vYfbd+uMkzTfMauwezYlJZG/t1XVsh4zex7go9QPfnwInMGSJgrvJ9kM1mbeHnTfLrFHIiSZ4WFYKmtPWsPywbHh30S4+uCfjuvYeAjzp2SmcmMpWpCUJXCRqCSIhKyyLksSdnmQD+FiV3Yrib2SYhPmWTUq8QooCPqNqn6jtqgyUNu8dPzH8z3JNwPuAa1qj90KyZr5wBBVF4+FFVbPvaeHXCZbNhfA1rrKh1TRFEDaUPmu2SpVo9N2pDwbuPS7qjryhM5cAGi2I8+Lf2Z/xipUgTp/My8RTdsbu/Lm65UFw3HTbOEMct2Nev6ebZDq75Rax9WdaZ3VJC0exWfxSUM= # DOCKER_PASSWORD
    - secure: b19wY7+mykJcNEL9rf6qwLQ2ABMf60KBHQ8BWUUl9dPThvM0WGAesFXEpK0MBS5m+qnkZQC6yLGZsL1hhMOYo8p8lwVmGPklrEEMBb9NIQ2pWUaV6QnP4cUQBECle8CBC29e8BYPtiKhShO/KQ659FPrPiIE/CynisDsCFJkXRcUs4H6+RR4P1ANsT0XV8UzY/VL9S9DDD7V//zVplo7LKU/MzzDT6XDRjdGRcgZ1WF+eARDcwsepic/JcmupOIiMDMXMinAj5dBGs1e2uQbKN9PNKxm4bXRkXGI8tsKlB5hiZFHBPfyI+yoDuGLyOtFoA7cSY7VdLT716p6fCz71OmmYRdquVZMgJUYejB2FRiExJ5IQPTZN1VB8l4N4XbA12ZJ3G/qwtGPEV47oPKUiSgAx8+2fc6JhVQn1lO+5U+pwLuPNu8TEnnJBC/6Irobrebq9KG0rwpVdbRTHzoRk+XPJIeOYmPSZ2wTga5u3pPjmx43dM6/6SOU38bXeogbOnM8aT+vawzHj4tlhLrj3f89eQQVU6+TubS1h+cquROpUtvRf0+JUs4QWeM6b8dX1hvV+7ti1/nJFG3jRVsFE5mC48e8S0duNNcHH4h8GrsBi4oc7GDBFWV3vJoVmtbpg4ZI4/PXyMC56LEjMP5UnoXd2Falm2CSWY0bsEZi6F0= # QUAY_PASSWORD

before_install:
  - sudo apt-get update
  - docker --version

script: ./build.sh

notifications:
  email:
    recipients:
      - travisci@crazymax.dev
    on_success: always
    on_failure: always
